function ax = batch_export_delta_Rate_Figs(dFR_table,varargin)
%BATCH_EXPORT_DELTA_RATE_FIGS  Export figures regarding delta-firing rate
%
%  batch_export_delta_Rate_Figs(dFR_table,'NAME',value,...);
%  --> dFR_table : Output by `compute_delta_FR`
%     * Should have 3 cells: 
%        + {1,1} -- 'BASAL' or 'PRE' (10 mins)
%        + {1,2} -- 'STIM'           (20 mins)
%        + {1,3} -- 'POST'           (15 mins)
%
%  --> <'NAME',value> pair syntax for setting optional parameters
%     * Default parameters are loaded from `defs.WholeTrialFigs`

pars = parseParameters('Export_Delta_Figs',varargin{:});
if iscell(dFR_table)
   curVec = [-1 1];
   for iIntensity = 1:3
      for iPolarity = 1:2
         figName = sprintf('%s-%s',...
                        pars.INTENSITY_LABEL{iIntensity},...
                        pars.CURRENT_LABEL{iPolarity});
         fig = figure('Name',figName,...
               'Units','Normalized',...
               'Color','w',...
               'Position',pars.FIG_POS);
         ax = axes(fig,'FontName','Arial',...
            'XColor','k','YColor','k',...
            'NextPlot','add',...
            'XLim',pars.XLIM,...
            'YLim',pars.YLIM);
         xlabel(ax,'Time (min)','FontName','Arial','FontSize',14,'Color','k');
         ylabel(ax,'\Delta \surd (FR)', 'FontName','Arial','FontSize',14,'Color','k'); 
         title(ax,figName,'FontName','Arial','FontSize',16,'Color','k');
         EPOCH_COLS = [];
         for iEpoch = 1:numel(dFR_table)
            T = dFR_table{iEpoch};
            T = T(...
               T.CurrentID==curVec(iPolarity) & ...
               T.ConditionID==iIntensity,:);
            c = pars.CONDITION_CUR_COL{iIntensity,iPolarity}.*pars.EPOCH_COL_FACTOR(iEpoch);
            ax = batch_export_delta_Rate_Figs(T,...
               'EPOCH_TS',pars.EPOCH_TS{iEpoch},...
               'CONDITION_ID',iIntensity,...
               'EPOCH_ID',iEpoch,...
               'CUR_ID',iPolarity,...
               'COLOR',c,...
               'AX',ax);  
            EPOCH_COLS = [EPOCH_COLS; c]; %#ok<AGROW>
         end
%          legend(ax,'Location','best',...
%             'FontSize',12,'FontName','Arial','TextColor','black');
         addEpochLabelsToAxes(ax,...
            'LABEL_HEIGHT',15,...
            'EPOCH_COL',EPOCH_COLS,...
            'TEXT_COL',[0 0 0]);
         fname = sprintf('%s-%s',...
                        pars.INTENSITY_FNAME{iIntensity},...
                        pars.CURRENT_FNAME{iPolarity});
         if exist(pars.OUT_FOLDER,'dir')==0
            mkdir(pars.OUT_FOLDER);
         end
         expAI(fig,fullfile(pars.OUT_FOLDER,fname));
         savefig(fig,fullfile(pars.OUT_FOLDER,[fname '.fig']));
         saveas(fig,fullfile(pars.OUT_FOLDER,[fname '.png']));
         delete(fig);
      end
   end
   return;
else
   if ~isa(pars.AX,'matlab.graphics.axis.Axes')
      error(['tDCS:' mfilename ':BadParams'],...
         ['\n\t->\t<strong>[BATCH_EXPORT_DELTA_RATE_FIGS]:</strong>\n ' ...
         'Bad syntax. Likely cause is not giving dFR_table as cell input.\n']);
   end
   ax = pars.AX;
end

YData = cell2mat(dFR_table.delta_sqrt_Rate);
XData = repmat(pars.EPOCH_TS,size(YData,1),1);
XData = XData(:);
YData = YData(:);
MaskData = cell2mat(dFR_table.mask);
MaskData = MaskData(:);
YData(MaskData) = [];
YData = YData.';
XData(MaskData) = [];
XData = XData.';
XData = XData + randn(1,numel(XData)).*pars.XJITTER;
XData = XData ./ 60 + 5; % Account for initial offset

dispName = sprintf('%s-%s (%s)',...
   pars.INTENSITY_LABEL{pars.CONDITION_ID},...
   pars.CURRENT_LABEL{pars.CUR_ID},...
   pars.EPOCH_NAMES{pars.EPOCH_ID});

% line(ax,XData,YData,...
%    'LineStyle','none',...
%    'Marker','o',...
%    'MarkerEdgeColor','none',...
%    'MarkerFaceColor',pars.COLOR,...
%    'MarkerSize',pars.MARKER_SIZE,...
%    'DisplayName',dispName);
scatter(ax,XData,YData,...
   'Marker','o',...
   'MarkerEdgeColor','none',...
   'MarkerFaceColor',pars.COLOR,...
   'SizeData',pars.MARKER_SIZE,...
   'MarkerFaceAlpha',0.25,...
   'DisplayName',dispName);


   

end