function fig = debug_EpochTimes(E,blockIndex,iStart,iStop,iSkip)
%DEBUG_EPOCHTIMES Debug "weird" recorded stim epochs
%
%  fig = debug_EpochTimes(E);
%  --> Chooses a row from `E` at random.
%  --> `E` is a table generated by `makeTable_stimEpochTimes`
%
%  fig = debug_EpochTimes(E,blockIndex);
%  --> Select using blockIndex
%  --> If blockIndex is a vector, returns multiple figures
%
%  fig = debug_EpochTimes(E,blockIndex,iStart,iStop,iSkip);
%  --> Can optionally specify start (`iStart`) & stop (`iStop) plot indices
%  --> Can set the number of samples to skip between plotted points
%     (`iSkip`)

if nargin < 5
   iSkip = 10000; % Points to skip between plot samples
end

if nargin < 4
   iStop = 90000000; % At most, this is 50 minutes @ 30 kHz
end

if nargin < 3
   iStart = 1;
end

if nargin < 2
   blockIndex = randi(size(E,1),1);
end

if numel(blockIndex) > 1
   fig = gobjects(size(blockIndex));
   for i = 1:numel(blockIndex)
      fig(i) = debug_EpochTimes(E,blockIndex(i),iStart,iStop,iSkip);
   end
   return;
end

bname = sprintf('TDCS-%02g',E.BlockID(blockIndex));
fig = figure(...
   'Name',sprintf('Debug Stim Epochs: %s',bname),...
   'Color','w',...
   'Units','Normalized',...
   'Position',[0.3 0.3 0.3 0.3]);
m = E.m{blockIndex};

if size(m,'board_dig_in_data',1) < 1
   annotation(fig,'textbox',[.2 .3 .4 .5],...
      'String',sprintf('Missing DIG data for %s',bname),...
      'FitBoxToText','on');
   return;
else
   iStop = min(iStop,size(m,'t',2));
   iStart = min(iStart,iStop-iSkip);
   iStart = max(iStart,1);
   plotIdx = iStart:iSkip:iStop;
   x = m.t(1,plotIdx)./60;
   y = m.board_dig_in_data(1,plotIdx);
   ax = axes(fig,...
      'XColor','k',...
      'YColor','k',...
      'LineWidth',1);
%    gfx__.simplePlot(...
%       ax,x,y,...
%       'Color','k',...
%       'MarkerFaceColor','k',...
%       'Marker','sq',...
%       'MarkerEdgeColor','none');
   line(...
      ax,x,y,...
      'Color','k',...
      'MarkerFaceColor','k',...
      'Marker','sq',...
      'MarkerEdgeColor','none',...
      'LineStyle','none');
   xlabel('Time (min)','FontName','Arial','FontSize',14,'Color','k');
   ylabel('Digital Value','FontName','Arial','FontSize',14,'Color','k');
   title(bname,...
      'FontName','Arial','FontSize',16,'Color','k','FontWeight','bold');
   xlim(ax,[0 1]);
   ylim(ax,[-0.1 1.1]);
   ax.YTick = [0 1];
   ax.YTickLabels = {'LOW','HIGH'};
end

end

