function fig = genLFPRainCloudPlots(LFP,varargin)
%GENLFPRAINCLOUDPLOTS  Generate RainCloudPlots for LFP bands
%
%  fig = genLFPRainCloudPlots(LFP);
%  fig = genLFPRainCloudPlots(LFP,pars);
%  fig = genLFPRainCloudPlots(__,'NAME',value,...);
%
%  -- inputs --
%  LFP : Table that has mean and median power density for bands by epoch
%
%  varargin : Can provide `pars` (defs.LFP) directly, or modify using
%              'NAME',value syntax
%
%  -- output --
%  fig : If figure handle is requested, then figures are not batch
%           saved/deleted, and they are returned as an array of figure
%           handles instead.

pars = parseParameters('LFP',varargin{:});
nBand = numel(pars.BANDS);
if nargout > 0
   fig = gobjects(3,nBand);
end
for iBand = 1:nBand
   if nargout > 0
      fig(:,iBand) = genRainCloudPlots(LFP(LFP.BandID==iBand,:),...
         'TAG',sprintf('LFP-%s',pars.BANDS{iBand}),...
         'XLIM',[-5 3],...
         'XTICK',[-4 -2 0 2],...
         'TEXT_TAGX_OFFSET',-5.5,...
         'TEXT_X_OFFSET',2,...
         'YTICK',[0 0.5 1],...
         'YTICKLAB',{'0','','1'},...
         'XLIM_CROSSED',[-6 4],...
         'XTICK_CROSSED',[-4 -2 0 2]...
         );
   else
      genRainCloudPlots(LFP(LFP.BandID==iBand,:),...
         'TAG',sprintf('LFP-%s',pars.BANDS{iBand}),...
         'XLIM',[-5 3],...
         'XTICK',[-4 -2 0 2],...
         'TEXT_TAGX_OFFSET',-5.5,...
         'TEXT_X_OFFSET',2,...
         'YTICK',[0 0.5 1],...
         'YTICKLAB',{'0','','1'},...
         'XLIM_CROSSED',[-6 4],...
         'XTICK_CROSSED',[-4 -2 0 2]...
         );
   end
end

end