function genWholeTrialFigs(S)
%GENWHOLETRIALFIGS    Generate whole trial figures for FR in tDCS analysis.
%
%   GENWHOLETRIALFIGS(S)

outDir = fullfile(defs.FileNames('OUTPUT_FIG_DIR'),'BOXPLOTS_Spikes');
if exist(outDir,'dir')==0
   mkdir(outDir);
end

% MAKE WHOLE-TRIAL RATE FIGURE BY ANIMAL
fig = figure('Name','Whole-trial FR by Animal',...
       'Units','Normalized',...
       'Position',[0.3 0.3 0.4 0.4],...
       'Color','w');
ax = axes(fig,'NextPlot','replacechildren',...
   'XColor','k',...
   'YColor','k',...
   'FontName','Arial',...
   'FontSize',13,...
   'Color','w');
boxplot(ax,log(S.Rate),S.Rat);
xlabel('Animal','FontName','Arial',...
   'Color','k','FontSize',14);
ylabel('log(rate)','FontName','Arial',...
   'Color','k','FontSize',14);
title('log(rate) by Animal','FontName','Arial',...
   'Color','k','FontSize',16,'FontWeight','bold');

expAI(fig,fullfile(outDir,'Rates_by-Animal'));
saveas(fig,fullfile(outDir,'Rates_by-Animal.png'));
savefig(fig,fullfile(outDir,'Rates_by-Animal.fig'));
delete(fig);

% BY TREATMENT
fig = figure('Name','Whole-trial FR by Treatment',...
       'Units','Normalized',...
       'Position',[0.3 0.4 0.4 0.4],...
       'Color','w');
ax = axes(fig,'NextPlot','replacechildren',...
   'XColor','k',...
   'YColor','k',...
   'FontName','Arial',...
   'FontSize',13,...
   'Color','w'); 
boxplot(ax,log(S.Rate),S.Condition);
xlabel('Treatment','FontName','Arial',...
   'Color','k','FontSize',14);
ylabel('log(rate)','FontName','Arial',...
   'Color','k','FontSize',14);   
title('log(rate) by Treatment','FontName','Arial',...
   'Color','k','FontSize',16,'FontWeight','bold');

expAI(fig,fullfile(outDir,'Rates_by-Treatment'));
saveas(fig,fullfile(outDir,'Rates_by-Treatment.png'));
savefig(fig,fullfile(outDir,'Rates_by-Treatment.fig'));
delete(fig);

% BY BOTH
fig = figure('Name','Whole-trial FR by Treatment by Rat',...
       'Units','Normalized',...
       'Position',[0.4 0.4 0.4 0.4],...
       'Color','w');
ax = axes(fig,'NextPlot','replacechildren',...
   'XColor','k',...
   'YColor','k',...
   'FontName','Arial',...
   'FontSize',13,...
   'Color','w');
boxplot(ax,log(S.Rate),[S.Rat,S.Condition]);
ylabel('log(rate)','FontName','Arial',...
   'Color','k','FontSize',14);
title('log(rate) by Rat & Treatment','FontName','Arial',...
   'Color','k','FontSize',16,'FontWeight','bold');

expAI(fig,fullfile(outDir,'Rates_by-Animal_by-Treatment'));
saveas(fig,fullfile(outDir,'Rates_by-Animal_by-Treatment.png'));
savefig(fig,fullfile(outDir,'Rates_by-Animal_by-Treatment.fig'));
delete(fig);

end